from fastapi import APIRouter, HTTPException, Depends
from typing import Dict, Any
from app.core.database import db
from app.routers.auth import get_current_user

router = APIRouter(prefix="/reports", tags=["Clinical Reports"])

@router.get("/{screening_id}")
def get_clinical_report(screening_id: str, current_user: dict = Depends(get_current_user)) -> Dict[str, Any]:
    screening = db.get_screening(screening_id)
    if not screening:
        raise HTTPException(status_code=404, detail="Screening report not found")

    # Enforce strict user ownership check
    # Only the patient who owns the record, or a verified doctor/admin, may read it.
    patient_id = screening.get("patient_id")
    if patient_id != current_user["id"] and current_user.get("role") not in ["doctor", "admin"]:
        raise HTTPException(
            status_code=403, 
            detail="Access denied: You do not have permission to view another user's clinical report."
        )

    # Dynamic patient details from actual user account and profile (no hardcoded demo fallbacks)
    patient = next((u for u in db.data.get("users", []) if u.get("id") == patient_id), None)
    profile = db.get_profile(patient_id) if patient_id else None

    patient_name = (
        (profile.get("full_name") if profile else None) or
        (patient.get("name") if patient else None) or
        screening.get("patient_name") or
        "Patient"
    )

    patient_payload = {
        "id": patient_id,
        "name": patient_name,
        "email": patient.get("email") if patient else "",
        "phone": patient.get("phone") if patient else "",
        "age": (profile.get("age") if profile else None) or (patient.get("age") if patient else None),
        "gender": (profile.get("gender") if profile else None) or (patient.get("gender") if patient else None) or "Not provided",
        "city": (profile.get("city") if profile else None) or (patient.get("city") if patient else None) or "Not provided"
    }

    return {
        "report_id": f"REP-{screening_id.upper()}",
        "facility": "Netra AI Clinical Tele-Screening Network",
        "accreditation": "ISO/IEC 27001 & ABDM Compliance Architecture",
        "screening": screening,
        "patient": patient_payload,
        "disclaimer": (
            "NOTICE: This report was generated by Netra AI diagnostic screening model (v1.4) "
            "utilizing deep convolutional feature extraction and Grad-CAM explainability localization. "
            "This report is intended to assist medical practitioners and triage at-risk patients, "
            "and does not constitute a substitute for in-person slit-lamp biomicroscopy or direct ophthalmoscopy."
        )
    }

@router.delete("/{screening_id}")
def delete_clinical_report(screening_id: str, current_user: dict = Depends(get_current_user)):
    """Delete a screening report. Only the owner or an admin can delete."""
    try:
        is_admin = current_user.get("role") == "admin"
        deleted = db.delete_screening(screening_id, current_user["id"], is_admin=is_admin)
        if not deleted:
            raise HTTPException(status_code=404, detail="Screening report not found.")
        return {"success": True, "message": "Clinical report deleted successfully."}
    except PermissionError as pe:
        raise HTTPException(status_code=403, detail=str(pe))
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete clinical report: {str(e)}")
